package com.vtheonly.recoveryscanner.support

import org.json.JSONObject
import java.io.File

/** Loads the deterministic fixtures generated by tools/gen_fixtures.py (PIL + ffmpeg). */
object Fixtures {

    val manifest: Map<String, JSONObject> by lazy {
        val text = javaClass.classLoader!!.getResourceAsStream("fixtures/fixtures.json")!!
            .bufferedReader().readText()
        val obj = JSONObject(text)
        obj.keys().asSequence().associateWith { obj.getJSONObject(it) }
    }

    fun bytes(name: String): ByteArray =
        javaClass.classLoader!!.getResourceAsStream("fixtures/$name")!!.readBytes()

    fun size(name: String): Long = manifest.getValue(name).getLong("size")

    fun sha256(name: String): String = manifest.getValue(name).getString("sha256")

    fun sha256(bytes: ByteArray): String =
        java.security.MessageDigest.getInstance("SHA-256").digest(bytes)
            .joinToString("") { "%02x".format(it) }

    /** Materializes a fixture (or arbitrary bytes) as a real temp file and returns it. */
    fun tempFile(name: String, content: ByteArray = bytes(name)): File =
        File.createTempFile("fx-", "-$name").apply { deleteOnExit(); writeBytes(content) }

    /** Creates a temp directory tree from (relativePath -> bytes) pairs. */
    fun tempDir(vararg files: Pair<String, ByteArray>): File =
        createTempDir("fx-tree").apply {
            deleteOnExit()
            for ((path, content) in files) {
                val f = File(this, path)
                f.parentFile?.mkdirs()
                f.writeBytes(content)
            }
        }
}
